### ISSUE TITLE
How to use the ECN_dist matrix

### ISSUE THREAD

**Issue by rainsoulsrx** [pse-ecn/expanded-cross-neighborhood#1]
Hi, I want to test the rerank code , and I generate queryset and testset feature matrix myself and using ECN_rerank(queryset, testset) to generate the ECN_dist matrix, I notice that there are many '1' elements in the matrix, so how can I use this matrix to evaluate the top-1 hitting rate?

**Comment by ssarfraz** [comment]
this is the final distance between your query and test set. just use this as you would use any other distance matrix.  The distance values are between 0 and 1, so 1 means very high distance and 0 means very close.
