### ISSUE TITLE
Is there any python implementation?

### ISSUE THREAD

**Issue by bjlgcxc** [pse-ecn/expanded-cross-neighborhood#2]
I wonder if there is any python implementation of ecn distance.
For that I implemented the ecn distance using python, while the evaluate result is terrible.

**Comment by andreas-eberle** [comment]
We haven't implemented it in python.

**Comment by bjlgcxc** [comment]
def re_ranking_ecn(q_g_dist, q_q_dist, g_g_dist, t=3, q=8):
    n_query = q_g_dist.shape[0]
    n_gallery = q_g_dist.shape[1]

    original_dist = np.concatenate(
        [np.concatenate([q_q_dist, q_g_dist], axis=1),
         np.concatenate([q_g_dist.T, g_g_dist], axis=1)],
        axis=0)
    original_dist = 2. - 2 * original_dist
    original_dist = np.transpose(1. * original_dist / np.max(original_dist, axis=0))
    initial_rank = np.argpartition(original_dist, range(1, q + 1))

    print('probe', n_query)
    print('gallery', n_gallery)
    print(original_dist.shape)

    top_t_nb = initial_rank[:, 1:t+1]

    t_ind = top_t_nb[n_query:, :].T
    next_2_tnbr = initial_rank[t_ind, 1:q+1]

    q_ind = top_t_nb[:n_query, :].T
    next_2_qnbr = initial_rank[q_ind, 1:q+1]
    del initial_rank
    gc.collect()

    next_2_tnbr = np.reshape(next_2_tnbr.T, (t*q, n_gallery))
    print(t_ind.shape, next_2_tnbr.shape)
    t_ind = np.concatenate((t_ind, next_2_tnbr))

    del next_2_tnbr
    gc.collect()
    next_2_qnbr = np.reshape(next_2_qnbr.T, (t*q, n_query))
    q_ind = np.concatenate((q_ind, next_2_qnbr))
    del next_2_qnbr
    gc.collect()

    t_nbr_dist = original_dist[t_ind, :n_query]
    t_nbr_dist = np.reshape(t_nbr_dist, (t+t*q, n_gallery, n_query))

    q_nbr_dist = original_dist[q_ind, n_query:]
    q_nbr_dist = np.reshape(q_nbr_dist, (t+t*q, n_query, n_gallery))
    q_nbr_dist = np.transpose(q_nbr_dist, (0, 2, 1))

    ECN_dist = np.squeeze(np.mean(q_nbr_dist+t_nbr_dist, axis=0))
    return ECN_dist.T

**Comment by andreas-repp** [comment]
@ssarfraz: Maybe you can help.

**Comment by ssarfraz** [comment]
Hi, I ported the code to python. you can  find it here (https://github.com/pse-ecn/expanded-cross-neighborhood/blob/master/ecn.py). Chek the readme for updates and usage.
@bjlgcxc  @andreas-eberle

**Comment by bjlgcxc** [comment]
ok, thank you for your help!
